### ISSUE TITLE
ClassNotFoundException on CDH-5.10.2

### ISSUE THREAD

**Issue by Myllyenko** [h2oai/sparkling-water#368]
When I execute `scala> val h2oContext = H2OContext.getOrCreate(sc)` in `sparkling-shell` attached to Spark 1.6.0 from CDH-5.10.2, I get the following exception:
```
java.util.ServiceConfigurationError: org.apache.spark.h2o.AnnouncementProvider: Provider org.apache.spark.h2o.RestAnnouncementProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)
        at scala.collection.Iterator$class.toStream(Iterator.scala:1143)
        at scala.collection.AbstractIterator.toStream(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toSeq(TraversableOnce.scala:261)
        at scala.collection.AbstractIterator.toSeq(Iterator.scala:1157)
        at org.apache.spark.h2o.AnnouncementServiceFactory$.create(AnnouncementService.scala:73)
        at org.apache.spark.h2o.H2OContext.<init>(H2OContext.scala:66)
        at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:293)
        at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:315)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:30)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:35)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:37)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:39)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:41)
        at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:43)
        at $iwC$$iwC$$iwC$$iwC.<init>(<console>:45)
        at $iwC$$iwC$$iwC.<init>(<console>:47)
        at $iwC$$iwC.<init>(<console>:49)
        at $iwC.<init>(<console>:51)
        at <init>(<console>:53)
        at .<init>(<console>:57)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1045)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1326)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:821)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:852)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:800)
        at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
        at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
        at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
        at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
        at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1064)
        at org.apache.spark.repl.Main$.main(Main.scala:35)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClientBuilder
        at org.apache.spark.h2o.RestAnnouncementProvider.<init>(AnnouncementService.scala:119)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 59 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClientBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 66 more
```

It looks like Apache Spark uses a different version of `http-client` than Cloudera Spark does and Sparkling Water relies on Apache's one as on provided dependency. I think it can be solved by shading `http-client` and including it into SW's assembly.

This exception was introduced with e16443ccad9a9fb1fd7e48ace8fd0176ac956bbf and occurs on SW 1.6.11 and 1.6.12.

**Comment by jakubhava** [comment]
Hi @Myllyenko, thanks for the error! I already commented on your PR. This should be fixed on `rel-1.6` branch which represents release branch of Sparkling Water for Spark 1.6.

**Comment by jakubhava** [comment]
Hi @Myllyenko, I have good news. At the end, we did a new release for Sparkling Water for Spark 1.6 with the proposed fix. You can get the new version here http://h2o-release.s3.amazonaws.com/sparkling-water/rel-1.6/13/index.html

**Comment by Myllyenko** [comment]
@jakubhava, it's nice to hear! Thank you :)

**Comment by Myllyenko** [comment]
@jakubhava, I've just noticed that solution proposed in my PR differs from the applied one: I've shaded the absent JARs so the deprecated method has been avoided.

Just letting you know in case you didn't consider this option. But in case you did and found any drawbacks, I would like to know what I missed.

**Comment by jakubhava** [comment]
Yup, we have this simple fix in the rest of the newer branches so wanted to apply the same fix here for the consistency.

We are trying to avoid shading when possible, however sometimes it's unavoidable.
