### ISSUE TITLE
I tried to use h2oContext = H2OContext.getOrCreate(sc) but I got an error 

### ISSUE THREAD

**Issue by MiraArikat** [h2oai/sparkling-water#160]
Im working using cloudera 5.8
sparkling water 1.6.8 
and h2o 3.10.0.7

**Comment by MiraArikat** [comment]
File "/home/cloudera/crime.py", line 94, in <module>
    h2oContext = H2OContext.getOrCreate(sc)
  File "build/bdist.linux-x86_64/egg/pysparkling/context.py", line 128, in getOrCreate
  File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o36.invoke.
: java.lang.AbstractMethodError

So that I replace this statment with the following 
h2oContext = pysparkling.context.H2OContext(sc)
#h2oContext = H2OContext.getOrCreate(sc)

and I got another error


Traceback (most recent call last):
  File "/home/cloudera/crime.py", line 142, in <module>
    df_weather = h2oContext.as_spark_frame(f_weather)
  File "build/bdist.linux-x86_64/egg/pysparkling/context.py", line 171, in as_spark_frame
  File "build/bdist.linux-x86_64/egg/pysparkling/context.py", line 34, in get_java_h2o_frame
AttributeError: 'H2OContext' object has no attribute '_jhc'

**Comment by mdymczyk** [comment]
This is most probably a duplicate of #127 - I've pushed a fix but it's still not released.

Also are you sure you are running CDH 5.8 and not 5.9?
